[package]
name = "comde"
version = "0.0.0"
authors = ["Brendan Molloy <brendan@bbqsrc.net>"]
edition = "2018"

[dependencies]
delegate = "0.2.0"
xz2 = { version = "0.1.6", optional = true }
snap = { version = "0.2", optional = true }
flate2 = { version = "1.0.11", optional = true }

[dev-dependencies]

[features]
xz = ["xz2"]
snappy = ["snap"]
deflate = ["flate2"]
